### ISSUE TITLE
Service Example only discoverable on same PC

### ISSUE THREAD

**Issue by jangernert** [librespot-org/libmdns#22]
I am just getting into mDNS, so this might be a silly question: I tried running the example on windows and used bonjour browser to discover the service. This works great when I run the browser on the same PC I run the example on. Bonjour browser on another PC in the network however doesn't pick the service up. There are a few printers and servers on the network which get discovered by both PCs.

Not sure if I am doing something wrong here. I went as far as disabling the windows firewall completely.

edit: it works when I run the example on a Linux machine. Then I can discover the service even on my phone.

**Comment by willstott101** [comment]
Hm, is it possible there is something about windows defender or an anti-virus here? It's pretty simple and we use existing rust libraries to bandage over OS differences. I haven't noticed issues when using librespot (a libmdns dependent) on windows - my android phone detects it.

**Comment by jangernert** [comment]
I disabled everything I could including some windows services that could have potentially blocked something and no other anti-virus software was installed. However windows is not my main operating system of choice. So I could have missed something.

**Comment by NfNitLoop** [comment]
Could this be related to https://github.com/librespot-org/libmdns/issues/33?  If your PC is on multiple networks, maybe it's choosing to advertise on only one of them, and not the one you expect.

**Comment by willstott101** [comment]
A potential fix for #33 has been merged. If you're still using libmdns and seeing issues please give that a try. I'll close this for now, re-open if you're still having issues. My only suggestion would be to try another mdns implementation (like python3's zeroconf), and see if it's working better.
