### ISSUE TITLE
mDNS response when device has multiple IP addresses

### ISSUE THREAD

**Issue by gbusker** [librespot-org/libmdns#23]
My device has a number of IP addresses associated with various if's.
Of course libmDNS chooses the wrong one when it reponds to mDNS requests :(

For discussion - what is the best approach?  Specify IP addresses for the service at responder.register() time ?
Or specify the IF device so the responder can work out both ipv4/6 addresses?

Thanks,
Gerd.

**Comment by willstott101** [comment]
Eventually if `IP_PKTINFO` is exposed in some of the low level rust networking libs we might be able to find the interface which an mDNS query came in from and respond with that specifically. Potentially we could work around that missing API by opening different sockets for each interface and therefore know both which interface received a request. The many-socket approach might let our original broadcast advertise _only_ the right address too.

**Comment by ArcticLampyrid** [comment]
> Potentially we could work around that missing API by opening different sockets for each interface.

Actually we don't bind to every interface but only to default interface.
Both `IP_ADD_MEMBERSHIP` and `IPV6_ADD_MEMBERSHIP` are only bound to default interface when UNSPECIFIED used. (At least on Windows)

#### [IP_MREQ](https://docs.microsoft.com/en-us/windows/win32/api/ws2ipdef/ns-ws2ipdef-ip_mreq)
> The local IPv4 address of the interface or the interface index on which the multicast group should be joined or dropped. This value is in network byte order. If this member specifies an IPv4 address of 0.0.0.0, the default IPv4 multicast interface is used.

#### [IPV6_MREQ](https://docs.microsoft.com/en-us/windows/win32/api/ws2ipdef/ns-ws2ipdef-ipv6_mreq)
> The interface index of the local interface on which the multicast group should be joined or dropped. If this member specifies an interface index of 0, the default multicast interface is used.

**Comment by CSRaghunandan** [comment]
Has anyone figured out a solution for this issue? I am running into the same problem as OP

**Comment by schnabel** [comment]
Hi. I also have the same problem as the OP. If I analysed this correctly, this behavior has bigger consequences. The host that is running this code might not be resolvable anymore.
My setup is a raspberry pi using librespot, docker, mpd, avahi-deamon. Docker spins up docker0 interface at 172.17.0.1 and every now and than all service addresses point to the docker interface like here:
```
= enp0s31f6 IPv4 Music Player @ myraspberry                      Music Player Daemon  local
   hostname = [myraspberry.local]
   address = [172.17.0.1]
   port = [6600]
   txt = []
```

**Comment by mstrug** [comment]
I've created PR which adds option to pass allowed to use IP list which fixes this problem: https://github.com/librespot-org/libmdns/pull/35
