### ISSUE TITLE
Multicast membership in multihomed environments does not work as intended

### ISSUE THREAD

**Issue by jaime-sense** [librespot-org/libmdns#33]
On a multihomed environment calling join_multicast_v4 or join_multicast_v6 with Ipv4Addr::UNSPECIFIED(0.0.0.0) or Ipv6Addr::UNSPECIFIED(::) does not have the intended effect of accepting queries on all interfaces. According to the [man pages](https://man7.org/linux/man-pages/man7/ip.7.html), calling bind with INADDR_ANY means the socket is bound to all local interfaces, however when calling setsockopt with INADDR_ANY, it means that the OS will pick an appropriate interface, NOT ALL interfaces as it was intended.

**Comment by willstott101** [comment]
Merged and released what is hopefully a fix for this in `0.7.3`. Please give it a try and see if it helps in your network setup.

I'm a little curious if the fix we have won't work for interfaces added after the responder starts (like USB dongles) - but perhaps we just re-open this issue if someone confirms that's a problem.
