### ISSUE TITLE
IPv6 interface binding

### ISSUE THREAD

**Issue by angelybo** [librespot-org/libmdns#44]
Hi, maybe I'm using this wrong, I can't seem to get the examples to advertise on ipv6 at all? 
It seems to register something but it never shows up in my mdns scan tools.
I've tried running the register and register_with_ip_list with a single item in the vector of my ipv6 addr - it always shows up on the ipv4 interface, showing a v4 IP. The register example shows up either my proper v4 IP or my docker IP.

I see that the enabled/disable ipv6 PRs are closed and from looking at the code, IPv6 should work out of the box?  
The use case I'm looking at is matter: https://github.com/project-chip/matter-rs
It currently works great on IPv4 but the end user clients only query over ipv6. I'd love to open a PR with IPv6 life imrpovements but I'm not sure where I should be looking?

**Comment by willstott101** [comment]
Thankyou for opening this... looks like this broke in f13beb1243b634db437b21cc25f475be3a715165 (0.7.2 works with IPv6 it would appear).

I'll have a look now and see if I can resolve - total oversight to not be testing ipv6 in CI, apologies.

**Comment by willstott101** [comment]
Could you try again from `main`? There was an issue where we attempted to join multicast twice on the same interface. Fixing that has fixed the new IPv6 test for me. I won't close this straight away in-case your issue is different in some way.

**Comment by angelybo** [comment]
This seems to show up with the right list of addresses. 
I think the rest of the issue is in my janky client tool. Seems okay to close this.

Thanks for the quick response!
